steps:
  # Build Container
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/crm-select-${_ENV}", "."]
  # Push Container
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/crm-select-${_ENV}"]
  # Deploy Containers
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args: ["cd", "~/scripts", "&&", "./update-${_ENV}.sh"]
