steps:
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - "-c"
      - "cd scripts && ls"

  # Build
  - name: "gcr.io/cloud-builders/docker"
    args:
      - build
      - -t
      - gcr.io/$PROJECT_ID/crm-select-${_ENV}
      - .

  # Push
  - name: "gcr.io/cloud-builders/docker"
    args:
      - push
      - gcr.io/$PROJECT_ID/crm-select-${_ENV}

  # Helm Auth
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - gcloud
      - auth
      - configure-docker
      - us-central1-docker.pkg.dev

  # Pull Helm Chart
  - name: gcr.io/$PROJECT_ID/helm
    args:
      - chart
      - pull
      - us-central1-docker.pkg.dev/${PROJECT_ID}/repo/enterprise:latest
    env:
      - HELM_EXPERIMENTAL_OCI=1
      - CLOUDSDK_COMPUTE_ZONE=us-central1-c
      - CLOUDSDK_CONTAINER_CLUSTER=etana

  # Unpack Helm Chart
  - name: gcr.io/$PROJECT_ID/helm
    args:
      - chart
      - export
      - us-central1-docker.pkg.dev/${PROJECT_ID}/repo/enterprise:latest
    env:
      - HELM_EXPERIMENTAL_OCI=1
      - CLOUDSDK_COMPUTE_ZONE=us-central1-c
      - CLOUDSDK_CONTAINER_CLUSTER=etana

  # Deploy
  - name: gcr.io/$PROJECT_ID/helm
    args:
      - upgrade
      - enterprise-${_ENV}
      - enterprise
      - -n
      - ${_ENV}
      - -f
      - ./values-${_ENV}.yaml
    env:
      - "CLOUDSDK_COMPUTE_ZONE=us-central1-c"
      - "CLOUDSDK_CONTAINER_CLUSTER=etana"

timeout: 1200s
