steps:
  # Build
  - name: "gcr.io/cloud-builders/docker"
    args:
      - build
      - -t
      - gcr.io/$PROJECT_ID/crm-select-${_ENV}
      - .

  # Push
  - name: "gcr.io/cloud-builders/docker"
    args:
      - push
      - gcr.io/$PROJECT_ID/crm-select-${_ENV}

  # Deploy
  - name: gcr.io/$PROJECT_ID/helm
    args:
      - upgrade
      - enterprise-${_ENV}
      - ~/ops/enterprise
      - -n
      - ${_ENV}
      - -f
      - ~/ops/values-${_ENV}.yaml
    env:
      - CLOUDSDK_COMPUTE_ZONE=us-central1-c
      - CLOUDSDK_CONTAINER_CLUSTER=etana
      - TILLERLESS=true
      - TILLER_NAMESPACE=${_ENV}

timeout: 1200s
