steps:
  # Build
  - name: "gcr.io/cloud-builders/docker"
    args:
      - build
      - -t
      - gcr.io/$PROJECT_ID/crm-select-${_ENV}
      - .

  # Push
  - name: "gcr.io/cloud-builders/docker"
    args:
      - push
      - gcr.io/$PROJECT_ID/crm-select-${_ENV}

  # Connect
  - name: gcr.io/cloud-builders/kubectl
    id: Configure kubectl
    args:
      - cluster-info
    env:
      - CLOUDSDK_COMPUTE_ZONE=us-central1-c
      - CLOUDSDK_CONTAINER_CLUSTER=etana
      - KUBECONFIG=/workspace/.kube/config

  # Deploy
  - name: gcr.io/$PROJECT_ID/helm
    entrypoint: "bash"
    args:
      - "-c"
      - |
        echo ${_KEY} | helm registry login -u _json_key_base64 --password-stdin https://us-central1-docker.pkg.dev
        helm chart pull us-central1-docker.pkg.dev/${PROJECT_ID}/repo/enterprise:0.1.0
        helm chart export us-central1-docker.pkg.dev/${PROJECT_ID}/repo/enterprise:0.1.0
        helm upgrade enterprise-${_ENV} enterprise -n ${_ENV} -f enterprise/values-${_ENV}.yaml
    env:
      - HELM_EXPERIMENTAL_OCI=1
      - CLOUDSDK_COMPUTE_ZONE=us-central1-c
      - CLOUDSDK_CONTAINER_CLUSTER=etana
      - TILLERLESS=true
      - TILLER_NAMESPACE=${_ENV}

timeout: 1200s
