steps:
  # Build Container
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/crm", "."]
  # Push Container
  - name: "gcr.io/cloud-builds/docker"
    args: ["push", "gcr.io/$PROJECT_ID/crm"]
