steps:
  # Build
  - name: "gcr.io/cloud-builders/docker"
    args:
      - build
      - -t
      - gcr.io/$PROJECT_ID/crm-select-${_ENV}
      - .

  # Push
  - name: "gcr.io/cloud-builders/docker"
    args:
      - push
      - gcr.io/$PROJECT_ID/crm-select-${_ENV}

  - name: "gcr.io/cloud-builders/docker"
    args:
      - build
      - -t
      - us-central1-docker.pkg.dev/etana-demo/repo/enterprise:latest
      - .

  # Deploy
  - name: gcr.io/$PROJECT_ID/helm
    args:
      - upgrade
      - enterprise-${_ENV}
      - enterprise
      - -n
      - ${_ENV}
      - -f
      - ./values-${_ENV}.yaml
    env:
      - "CLOUDSDK_COMPUTE_ZONE=us-central1-c"
      - "CLOUDSDK_CONTAINER_CLUSTER=etana"

timeout: 1200s
