steps:
  # Build
  - name: "gcr.io/cloud-builders/docker"
    args:
      - build
      - -t
      - gcr.io/$PROJECT_ID/crm-select-${_ENV}
      - .

  # Push
  - name: "gcr.io/cloud-builders/docker"
    args:
      - push
      - gcr.io/$PROJECT_ID/crm-select-${_ENV}

  # Cluster
  - name: gcr.io/cloud-builders/kubectl
    args:
      - cluster-info
    env:
      - CLOUDSDK_COMPUTE_REGION=us-central1-c
      - CLOUDSDK_CONTAINER_CLUSTER=etana
      - KUBECONFIG=/workspace/.kube/config

  # Deploy
  - name: gcr.io/$PROJECT_ID/helm
    args:
      - helm
      - upgrade
      - enterprise-dev,
      - ./ops/enterprise,
      - -n,
      - dev,
      - -f,
      - ./ops/values-dev.yaml,

timeout: 1200s
